apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80    # Exposed port outside the cluster
      targetPort: 8081  # Port inside the container
  type: LoadBalancer  # Expose the app externally
